# Dependencies
markdown:         kramdown
#highlighter:      pygments
### ref: https://help.github.com/articles/page-build-failed-config-file-error/#fixing-highlighting-errors
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true         ## removed from jekyll 3 and above 
## refer: https://jekyllrb.com/docs/upgrading/2-to-3/#relative-permalink-support-removed
## refer: https://help.github.com/articles/using-jekyll-with-pages/#troubleshooting

# Setup
title:            Tasdik Rahman
description:      'tail -f /var/log/life*'

url:              https://www.tasdikrahman.com
# url:              http://0.0.0.0:4000/
baseurl:          /
logo:             /content/images/dp.jpg

author:
  name:           'Tasdik Rahman'
  url:            https://plus.google.com/+TasdikRahman

paginate:         5

disqus_shortname: tasdikrahman

github:
  repo:           https://github.com/tasdikrahman/

gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-mentions

jekyll-mentions:
  base_url: https://twitter.com

jekyll-archives:
  enabled: []
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

twitter: '@tasdikrahman'

kramdown:
  # Enable GitHub Flavored Markdown (fenced code blocks)
  input: GFM
